###################################################################
#                     BROWSER CONFIGURATION                       #
###################################################################
#---------------------------
# :firefox=> "FireFox"
# :chrome => "Chrome"
#---------------------------
default_browser: :firefox
test_page_address: http://google.co.uk
